       """Test the errno module
          Roger E. Masse
    1: """
       
    1: import errno
    1: from test import test_support
    1: import unittest
       
    1: std_c_errors = frozenset(['EDOM', 'ERANGE'])
       
    2: class ErrnoAttributeTests(unittest.TestCase):
       
    1:     def test_for_improper_attributes(self):
               # No unexpected attributes should be on the module.
    3:         for error_code in std_c_errors:
    2:             self.assertTrue(hasattr(errno, error_code),
    2:                             "errno is missing %s" % error_code)
       
    1:     def test_using_errorcode(self):
               # Every key value in errno.errorcode should be on the module.
   86:         for value in errno.errorcode.itervalues():
   85:             self.assertTrue(hasattr(errno, value), 'no %s attr in errno' % value)
       
       
    2: class ErrorcodeTests(unittest.TestCase):
       
    1:     def test_attributes_in_errorcode(self):
   91:         for attribute in errno.__dict__.iterkeys():
   90:             if attribute.isupper():
   86:                 self.assertIn(getattr(errno, attribute), errno.errorcode,
   86:                               'no %s attr in errno.errorcode' % attribute)
       
       
    1: def test_main():
    1:     test_support.run_unittest(ErrnoAttributeTests, ErrorcodeTests)
       
       
    1: if __name__ == '__main__':
>>>>>>     test_main()
